<#-- @ftlvariable name="model" type="api.maven.plugin.angular.client.data.TypeScriptDTO" -->
<#if model.dependencies?has_content>
<#list model.dependencies as dependency>
import {${dependency.identifiers?join(", ")}} from '${dependency.path}';
</#list>

</#if>
/**
 * Autogenerated DTO interface representing the java class ${model.className}
 */
export interface ${model.name}<#if model.typeArguments?has_content><${model.typeArguments?join(", ")}></#if><#if model.extendedDTO??> extends ${model.extendedDTO.name}</#if> {

<#list model.fields?keys as fieldName>
    ${fieldName}${model.fields[fieldName].optional?then("?", "")}: ${model.fields[fieldName].name};
</#list>

}