<#-- @ftlvariable name="model" type="de.devx.project.assertj.assertion.gennerator.data.AssertJAssertModel" -->
package ${model.packageName};

/**
 * Autogenerated assert of the {@link ${model.name}}.
 *
 * @see Abstract${model.assertName} for extending this assert
 */
public final class ${model.assertName}<#if model.typeArguments?has_content><${model.typeArguments?map(typeArgument -> typeArgument.definition)?join(", ")}></#if> extends Abstract${model.assertName}<<#list model.typeArguments as typeArgument>${typeArgument.definition}, </#list>${model.assertName}<#if model.typeArguments?has_content><${model.typeArguments?map(typeArgument -> typeArgument.definition)?join(", ")}></#if>, ${model.name}<#if model.typeArguments?has_content><${model.typeArguments?map(typeArgument -> typeArgument.definition)?join(", ")}></#if>> {

    /**
     * Autogenerated constructor
     *
     * @param actual the actual value
     */
    public ${model.assertName}(${model.name}<#if model.typeArguments?has_content><${model.typeArguments?map(a -> a.definition)?join(", ")}></#if> actual) {
        super(actual, ${model.assertName}.class);
    }
}