package de.devx.project.commons.client.typescript;


import de.devx.project.commons.client.typescript.data.TypeScriptBrandedTypeModel;
import de.devx.project.commons.client.typescript.data.TypeScriptDTOFieldModel;
import de.devx.project.commons.client.typescript.data.TypeScriptDTOModel;
import de.devx.project.commons.client.typescript.data.TypeScriptEnumModel;
import de.devx.project.commons.client.typescript.data.TypeScriptTypeModel;
import de.devx.project.commons.client.typescript.properties.TypeScriptClientGeneratorProperties;
import de.devx.project.commons.client.typescript.properties.TypeScriptPackageAlias;
import de.devx.project.commons.client.typescript.properties.TypeScriptTypeAlias;
import de.devx.project.commons.test.io.TestSourceFileGenerator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Nested;

import java.io.IOException;
import java.util.List;
import java.util.Set;

import static java.util.Collections.emptyList;
import static java.util.Collections.emptySet;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;

class TypescriptClientGeneratorTest {

    private static final TypeScriptPackageAlias PACKAGE_ALIAS = new TypeScriptPackageAlias("de.test.typescript.client", null);

    private final TestSourceFileGenerator fileGenerator = new TestSourceFileGenerator();

    @Nested
    class TypeGenerations {

        private final TypescriptClientGenerator<TypeScriptClientGeneratorProperties> generator = new TypescriptClientGenerator<>(
                fileGenerator,
                new TypeScriptClientGeneratorProperties(emptyList(), List.of(PACKAGE_ALIAS), null)
        );

        @Test
        void testGenerateEnum() throws IOException {
            var model = new TypeScriptEnumModel();
            model.setName("TestType");
            model.setClassName("de.test.typescript.client.type.TestType");
            model.setValues(List.of("A", "B", "C"));

            generator.generateEnum(model);

            var generatedEnum = fileGenerator.getFileContent("type", "TestType");
            assertThat(generatedEnum.isPresent(), is(true));
            assertThat(generatedEnum.get(), is("""
                /**
                 * Autogenerated enum type representing de.test.typescript.client.type.TestType
                 */
                export type TestType = 'A' | 'B' | 'C';
                                
                /**
                 * Autogenerated constant array containing all allowed enum values of TestType
                 */
                export const TestTypes: TestType[] = ['A', 'B', 'C'];
                                
                /**
                 * Autogenerated function for type checking
                 *
                 * @param {*} value the value to check
                 * @returns {boolean} true if value is of type TestType
                 */
                export function isTestType(value: unknown): value is TestType {
                    return typeof value === 'string' && TestTypes.includes(value as TestType);
                }
                                
                /**
                * Autogenerated function for casting
                *
                * @param {*} value the value to cast
                * @returns {TestType} the value
                */
                export function castToTestType(value: unknown): TestType {
                    if (isTestType(value)) {
                        return value;
                    }
                                
                    throw new Error('CastError: Failed to cast value to a TestType');
                }
                """));
        }

        @Test
        void testGenerateDTO() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("requiredField", new TypeScriptTypeModel("number", false, emptySet(), null)),
                    new TypeScriptDTOFieldModel("optionalField", new TypeScriptTypeModel("string", true, emptySet(), null))
            ));

            generator.generateDTO(model);

            var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
            assertThat(generatedDTO.isPresent(), is(true));
            assertThat(generatedDTO.get(), is("""
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO {
                                
                    requiredField: number;
                    optionalField?: string;
                                
                }
                """));
        }

        @Test
        void testGenerateGenericDTO() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setTypeArguments(List.of("T"));
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("T", false, emptySet(), null))
            ));

            generator.generateDTO(model);

            var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
            assertThat(generatedDTO.isPresent(), is(true));
            assertThat(generatedDTO.get(), is("""
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO<T> {
                                
                    field: T;
                                
                }
                """));
        }

        @Test
        void testGenerateDTOWithImports() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("SecondTestDTO", false, Set.of("de.test.typescript.client.dto.SecondTestDTO"), null))
            ));

            generator.generateDTO(model);

            var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
            assertThat(generatedDTO.isPresent(), is(true));
            assertThat(generatedDTO.get(), is("""
                import { type SecondTestDTO } from 'dto/SecondTestDTO';
                                
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO {
                                
                    field: SecondTestDTO;
                                
                }
                """));
        }

        @Test
        void testGenerateExtendedDTO() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setExtendedDTO(new TypeScriptTypeModel("BaseDTO", false, Set.of("de.test.typescript.client.dto.BaseDTO"), null));
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("string", false, emptySet(), null))
            ));

            generator.generateDTO(model);

            var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
            assertThat(generatedDTO.isPresent(), is(true));
            assertThat(generatedDTO.get(), is("""
                import { type BaseDTO } from 'dto/BaseDTO';

                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO extends BaseDTO {

                    field: string;

                }
                """));
        }

        @Test
        void testGenerateBrandedType() throws IOException {
            var model = new TypeScriptBrandedTypeModel();
            model.setName("UserID");
            model.setClassName("de.test.typescript.client.dto.UserID");
            model.setUnderlyingTsType("number");

            generator.generateBrandedType(model);

            var generatedType = fileGenerator.getFileContent("dto", "UserID");
            assertThat(generatedType.isPresent(), is(true));
            assertThat(generatedType.get(), is("""
                    /**
                     * Autogenerated branded type representing de.test.typescript.client.dto.UserID
                     */
                    export type UserID = number & { __brand: 'de.test.typescript.client.dto.UserID' };
                    """));
        }
    }

    @Nested
    class ZodSchema {

        private final TypescriptClientGenerator<TypeScriptClientGeneratorProperties> generator = new TypescriptClientGenerator<>(fileGenerator, new TypeScriptClientGeneratorProperties(emptyList(), List.of(PACKAGE_ALIAS), null, true));;

        @Test
        void testGenerateEnumZodSchema() throws IOException {
            var model = new TypeScriptEnumModel();
            model.setName("TestType");
            model.setClassName("de.test.typescript.client.type.TestType");
            model.setValues(List.of("A", "B", "C"));

            generator.generateEnum(model);

            var generatedSchema = fileGenerator.getFileContent("type", "TestTypeSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                import { z } from 'zod';

                /**
                 * Autogenerated Zod schema for de.test.typescript.client.type.TestType
                 */
                export const TestTypeSchema = z.enum(['A', 'B', 'C']);
                """));
        }

        @Test
        void testGenerateDTOZodSchema() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("requiredField", new TypeScriptTypeModel("number", false, emptySet(), "z.number()")),
                    new TypeScriptDTOFieldModel("optionalField", new TypeScriptTypeModel("string", true, emptySet(), "z.string()"))
            ));

            generator.generateDTO(model);

            var generatedSchema = fileGenerator.getFileContent("dto", "TestDTOSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                import { z } from 'zod';

                /**
                 * Autogenerated Zod schema for de.test.typescript.client.dto.TestDTO
                 */
                export const TestDTOSchema = z.object({

                    requiredField: z.number(),
                    optionalField: z.string().optional(),

                });
                """));
        }

        @Test
        void testGenerateGenericDTOSkipsZodSchema() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setTypeArguments(List.of("T"));
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("T", false, emptySet(), "z.unknown()"))
            ));

            generator.generateDTO(model);

            assertThat(fileGenerator.getFileContent("dto", "TestDTOSchema").isPresent(), is(false));
        }

        @Test
        void testGenerateDTOZodSchemaWithImports() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("SecondTestDTO", false, Set.of("de.test.typescript.client.dto.SecondTestDTO"), "SecondTestDTOSchema"))
            ));

            generator.generateDTO(model);

            var generatedSchema = fileGenerator.getFileContent("dto", "TestDTOSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                import { z } from 'zod';
                import { SecondTestDTOSchema } from 'dto/SecondTestDTOSchema';

                /**
                 * Autogenerated Zod schema for de.test.typescript.client.dto.TestDTO
                 */
                export const TestDTOSchema = z.object({

                    field: SecondTestDTOSchema,

                });
                """));
        }

        @Test
        void testGenerateBrandedType() throws IOException {
            var model = new TypeScriptBrandedTypeModel();
            model.setName("UserID");
            model.setClassName("de.test.typescript.client.type.UserID");
            model.setUnderlyingTsType("number");
            model.setUnderlyingZodSchema("z.number()");

            generator.generateBrandedType(model);

            var generatedType = fileGenerator.getFileContent("type", "UserID");
            assertThat(generatedType.isPresent(), is(true));
            assertThat(generatedType.get(), is("""
                    import { z } from 'zod';
                    import { UserIDSchema } from 'type/UserIDSchema';

                    /**
                     * Autogenerated branded type representing de.test.typescript.client.type.UserID
                     */
                    export type UserID = z.infer<typeof UserIDSchema>;
                    """));
        }

        @Test
        void testGenerateBrandedTypeZodSchema() throws IOException {
            var model = new TypeScriptBrandedTypeModel();
            model.setName("UserID");
            model.setClassName("de.test.typescript.client.type.UserID");
            model.setUnderlyingTsType("number");
            model.setUnderlyingZodSchema("z.number()");

            generator.generateBrandedType(model);

            var generatedSchema = fileGenerator.getFileContent("type", "UserIDSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                    import { z } from 'zod';

                    /**
                     * Autogenerated Zod schema for de.test.typescript.client.type.UserID
                     */
                    export const UserIDSchema = z.number().brand<'de.test.typescript.client.type.UserID'>();
                    """));
        }

        @Test
        void testGenerateExtendedDTOZodSchema() throws IOException {
            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setExtendedDTO(new TypeScriptTypeModel("BaseDTO", false, Set.of("de.test.typescript.client.dto.BaseDTO"), "BaseDTOSchema"));
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("string", false, emptySet(), "z.string()"))
            ));

            generator.generateDTO(model);

            var generatedSchema = fileGenerator.getFileContent("dto", "TestDTOSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                import { z } from 'zod';
                import { BaseDTOSchema } from 'dto/BaseDTOSchema';

                /**
                 * Autogenerated Zod schema for de.test.typescript.client.dto.TestDTO
                 */
                export const TestDTOSchema = BaseDTOSchema.extend({

                    field: z.string(),

                });
                """));
        }
    }

    @Nested
    class WithAlias {
        @Test
        void testGenerateDTOZodSchemaWithAliasedFieldFallback() throws IOException {
            var alias = new TypeScriptTypeAlias();
            alias.setClassName("com.example.LocalDate");
            alias.setType("LocalDateRep");
            alias.setDependency("my-date-lib");

            var generatorWithAlias = new TypescriptClientGenerator<>(fileGenerator, new TypeScriptClientGeneratorProperties(
                    List.of(alias), List.of(PACKAGE_ALIAS), null, true));

            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("date", new TypeScriptTypeModel("LocalDateRep", false, Set.of("com.example.LocalDate"), "z.custom<LocalDateRep>()"))
            ));

            generatorWithAlias.generateDTO(model);

            var generatedSchema = fileGenerator.getFileContent("dto", "TestDTOSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                    import { z } from 'zod';
                    import { LocalDateRep } from 'my-date-lib';

                    /**
                     * Autogenerated Zod schema for de.test.typescript.client.dto.TestDTO
                     */
                    export const TestDTOSchema = z.object({

                        date: z.custom<LocalDateRep>(),

                    });
                    """));
        }

        @Test
        void testGenerateDTOZodSchemaWithAliasedFieldDependency() throws IOException {
            var alias = new TypeScriptTypeAlias();
            alias.setClassName("com.example.LocalDate");
            alias.setType("LocalDateRep");
            alias.setDependency("my-date-lib");
            alias.setZodSchema("LocalDateRepSchema");
            alias.setZodSchemaDependency("my-date-lib");

            var generatorWithAlias = new TypescriptClientGenerator<>(fileGenerator, new TypeScriptClientGeneratorProperties(
                    List.of(alias), List.of(PACKAGE_ALIAS), null, true));

            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("date", new TypeScriptTypeModel("LocalDateRep", false, Set.of("com.example.LocalDate"), "LocalDateRepSchema"))
            ));

            generatorWithAlias.generateDTO(model);

            var generatedSchema = fileGenerator.getFileContent("dto", "TestDTOSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                    import { z } from 'zod';
                    import { LocalDateRepSchema } from 'my-date-lib';

                    /**
                     * Autogenerated Zod schema for de.test.typescript.client.dto.TestDTO
                     */
                    export const TestDTOSchema = z.object({

                        date: LocalDateRepSchema,

                    });
                    """));
        }

        @Test
        void testGenerateDTOZodSchemaWithAliasedFieldPath() throws IOException {
            var alias = new TypeScriptTypeAlias();
            alias.setClassName("com.example.LocalDate");
            alias.setType("LocalDateRep");
            alias.setPath("shared");
            alias.setZodSchema("LocalDateRepSchema");
            alias.setZodSchemaPath("shared/local-date-rep.schema");

            var generator = new TypescriptClientGenerator<>(fileGenerator, new TypeScriptClientGeneratorProperties(
                    List.of(alias), List.of(PACKAGE_ALIAS), null, true));

            var model = new TypeScriptDTOModel();
            model.setName("TestDTO");
            model.setClassName("de.test.typescript.client.dto.TestDTO");
            model.setFields(List.of(
                    new TypeScriptDTOFieldModel("date", new TypeScriptTypeModel("LocalDateRep", false, Set.of("com.example.LocalDate"), "LocalDateRepSchema"))
            ));

            generator.generateDTO(model);

            var generatedSchema = fileGenerator.getFileContent("dto", "TestDTOSchema");
            assertThat(generatedSchema.isPresent(), is(true));
            assertThat(generatedSchema.get(), is("""
                    import { z } from 'zod';
                    import { LocalDateRepSchema } from 'shared/local-date-rep.schema';

                    /**
                     * Autogenerated Zod schema for de.test.typescript.client.dto.TestDTO
                     */
                    export const TestDTOSchema = z.object({

                        date: LocalDateRepSchema,

                    });
                    """));
        }
    }
}