package de.devx.project.commons.client.typescript;


import de.devx.project.commons.client.typescript.data.TypeScriptDTOFieldModel;
import de.devx.project.commons.client.typescript.data.TypeScriptDTOModel;
import de.devx.project.commons.client.typescript.data.TypeScriptEnumModel;
import de.devx.project.commons.client.typescript.data.TypeScriptTypeModel;
import de.devx.project.commons.client.typescript.properties.TypeScriptClientGeneratorProperties;
import de.devx.project.commons.client.typescript.properties.TypeScriptPackageAlias;
import de.devx.project.commons.test.io.TestSourceFileGenerator;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.List;
import java.util.Set;

import static java.util.Collections.emptySet;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;

class TypescriptClientGeneratorTest {

    private static final TypeScriptPackageAlias PACKAGE_ALIAS = new TypeScriptPackageAlias("de.test.typescript.client", null);

    private final TestSourceFileGenerator fileGenerator = new TestSourceFileGenerator();
    private final TypescriptClientGenerator<TypeScriptClientGeneratorProperties> generator = new TypescriptClientGenerator<>(fileGenerator, TypeScriptClientGeneratorProperties.builder()
            .packageAliases(List.of(PACKAGE_ALIAS))
            .build());

    @Test
    void testGenerateEnum() throws IOException {
        var model = new TypeScriptEnumModel();
        model.setName("TestType");
        model.setClassName("de.test.typescript.client.type.TestType");
        model.setValues(List.of("A", "B", "C"));

        generator.generateEnum(model);

        var generatedEnum = fileGenerator.getFileContent("type", "TestType");
        assertThat(generatedEnum.isPresent(), is(true));
        assertThat(generatedEnum.get(), is("""
                /**
                 * Autogenerated enum type representing de.test.typescript.client.type.TestType
                 */
                export type TestType = 'A' | 'B' | 'C';
                                
                /**
                 * Autogenerated constant array containing all allowed enum values of TestType
                 */
                export const TestTypes: TestType[] = ['A', 'B', 'C'];
                                
                /**
                 * Autogenerated function for type checking
                 *
                 * @param {*} value the value to check
                 * @returns {boolean} true if value is of type TestType
                 */
                export function isTestType(value: unknown): value is TestType {
                    return typeof value === 'string' && TestTypes.includes(value as TestType);
                }
                                
                /**
                * Autogenerated function for casting
                *
                * @param {*} value the value to cast
                * @returns {TestType} the value
                */
                export function castToTestType(value: unknown): TestType {
                    if (isTestType(value)) {
                        return value;
                    }
                                
                    throw new Error('CastError: Failed to cast value to a TestType');
                }
                """));
    }

    @Test
    void testGenerateDTO() throws IOException {
        var model = new TypeScriptDTOModel();
        model.setName("TestDTO");
        model.setClassName("de.test.typescript.client.dto.TestDTO");
        model.setFields(List.of(
                new TypeScriptDTOFieldModel("requiredField", new TypeScriptTypeModel("number", false, emptySet())),
                new TypeScriptDTOFieldModel("optionalField", new TypeScriptTypeModel("string", true, emptySet()))
        ));

        generator.generateDTO(model);

        var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
        assertThat(generatedDTO.isPresent(), is(true));
        assertThat(generatedDTO.get(), is("""
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO {
                                
                    requiredField: number;
                    optionalField?: string;
                                
                }
                """));
    }

    @Test
    void testGenerateGenericDTO() throws IOException {
        var model = new TypeScriptDTOModel();
        model.setName("TestDTO");
        model.setClassName("de.test.typescript.client.dto.TestDTO");
        model.setTypeArguments(List.of("T"));
        model.setFields(List.of(
                new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("T", false, emptySet()))
        ));

        generator.generateDTO(model);

        var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
        assertThat(generatedDTO.isPresent(), is(true));
        assertThat(generatedDTO.get(), is("""
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO<T> {
                                
                    field: T;
                                
                }
                """));
    }

    @Test
    void testGenerateDTOWithImports() throws IOException {
        var model = new TypeScriptDTOModel();
        model.setName("TestDTO");
        model.setClassName("de.test.typescript.client.dto.TestDTO");
        model.setFields(List.of(
                new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("SecondTestDTO", false, Set.of("de.test.typescript.client.dto.SecondTestDTO")))
        ));

        generator.generateDTO(model);

        var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
        assertThat(generatedDTO.isPresent(), is(true));
        assertThat(generatedDTO.get(), is("""
                import { type SecondTestDTO } from 'dto/SecondTestDTO';
                                
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO {
                                
                    field: SecondTestDTO;
                                
                }
                """));
    }

    @Test
    void testGenerateExtendedDTO() throws IOException {
        var model = new TypeScriptDTOModel();
        model.setName("TestDTO");
        model.setClassName("de.test.typescript.client.dto.TestDTO");
        model.setExtendedDTO(new TypeScriptTypeModel("BaseDTO", false, Set.of("de.test.typescript.client.dto.BaseDTO")));
        model.setFields(List.of(
                new TypeScriptDTOFieldModel("field", new TypeScriptTypeModel("string", false, emptySet()))
        ));

        generator.generateDTO(model);

        var generatedDTO = fileGenerator.getFileContent("dto", "TestDTO");
        assertThat(generatedDTO.isPresent(), is(true));
        assertThat(generatedDTO.get(), is("""
                import { type BaseDTO } from 'dto/BaseDTO';
                                
                /**
                 * Autogenerated DTO interface representing the java class de.test.typescript.client.dto.TestDTO
                 */
                export interface TestDTO extends BaseDTO {
                                
                    field: string;
                                
                }
                """));
    }
}