<#-- @ftlvariable name="packageName" type="java.lang.String" -->
<#-- @ftlvariable name="models" type="java.util.List<de.devx.project.freemarker.generator.data.FtlTemplateModel>" -->
package ${packageName};

/**
 * Autogenerated FreeMarker templates
 */
public class FreemarkerTemplate<M> {

    <#list models as model>
    public static final FreemarkerTemplate<${model.modelClassName}> ${model.templateIdentifier} = new FreemarkerTemplate<>("${model.templatePath}", ${model.modelClassName}.class);
    </#list>

    private final String templatePath;
    private final Class<M> modelType;

    private FreemarkerTemplate(String templatePath, Class<M> modelType) {
        this.templatePath = templatePath;
        this.modelType = modelType;
    }

    public String getTemplatePath() {
        return templatePath;
    }

    public Class<M> getModelType() {
        return modelType;
    }
}
