<#-- @ftlvariable name="packageName" type="java.lang.String" -->
package ${packageName};

/**
 * Autogenerated FreeMarker templates
 */
public class FreemarkerTemplate<M> {

    public static <M> FreemarkerTemplate<M> of(String templatePath, Class<M> modelType) {
        return new FreemarkerTemplate<>(templatePath, modelType);
    }

    private final String templatePath;
    private final Class<M> modelType;

    private FreemarkerTemplate(String templatePath, Class<M> modelType) {
        this.templatePath = templatePath;
        this.modelType = modelType;
    }

    public String getTemplatePath() {
        return templatePath;
    }

    public Class<M> getModelType() {
        return modelType;
    }
}
