<#-- @ftlvariable name="model" type="de.devx.project.freemarker.generator.data.FtlTemplateModel" -->
<#-- @ftlvariable name="imports" type="java.util.List<java.lang.String>" -->
package ${model.packageName};

<#list imports as import>
import ${import};
</#list>

/**
 * Autogenerated data model for the FreeMarker template {@code ${model.templateName}.ftl}.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ${model.modelClassName} {
<#list model.variables as variable>

    private ${variable.simpleType} ${variable.name};
</#list>
}
