<#-- @ftlvariable name="packageName" type="java.lang.String" -->
<#-- @ftlvariable name="groupClassName" type="java.lang.String" -->
<#-- @ftlvariable name="imports" type="java.util.List<java.lang.String>" -->
<#-- @ftlvariable name="templates" type="java.util.List<de.devx.project.freemarker.generator.data.FtlTemplateModel>" -->
package ${packageName};
<#if imports?has_content>

<#list imports as import>
import ${import};
</#list>
</#if>

/**
 * Autogenerated FreeMarker template constants.
 */
public class ${groupClassName} {

    <#list templates as model>
    public static final FreemarkerTemplate<${model.modelClassName}> ${model.templateIdentifier} = FreemarkerTemplate.of("${model.templatePath}", ${model.modelClassName}.class);
    </#list>

    private ${groupClassName}() {
    }
}
