package de.devx.project.freemarker.generator;

import de.devx.project.commons.test.io.TestSourceFileGenerator;
import de.devx.project.freemarker.generator.data.FtlTemplateModel;
import de.devx.project.freemarker.generator.data.FtlVariableModel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Collections;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class FtlModelGeneratorTest {

    private static final String PACKAGE_NAME = "com.example.templates";

    private final TestSourceFileGenerator sourceFileGenerator = new TestSourceFileGenerator();

    private final FtlModelGenerator sut = new FtlModelGenerator(sourceFileGenerator);

    @BeforeEach
    void setUp() {
        sourceFileGenerator.reset();
    }

    @Test
    void testGenerateModelWithSingleJavaLangField() throws IOException {
        var model = new FtlTemplateModel(
                "WelcomeEmail",
                "WelcomeEmail",
                PACKAGE_NAME,
                "WelcomeEmail.ftl",
                List.of(new FtlVariableModel("subject", "String", List.of()))
        );

        sut.generateModel(model);

        assertThat(sourceFileGenerator.getCreatedSourceFileNames())
                .containsExactly(PACKAGE_NAME + ".WelcomeEmailModel");

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "WelcomeEmailModel"))
                .isPresent()
                .get()
                .isEqualTo("""
                        package com.example.templates;

                        import lombok.AllArgsConstructor;
                        import lombok.Data;
                        import lombok.NoArgsConstructor;

                        /**
                         * Autogenerated data model for the FreeMarker template {@code WelcomeEmail.ftl}.
                         */
                        @Data
                        @AllArgsConstructor
                        @NoArgsConstructor
                        public class WelcomeEmailModel {

                            private String subject;
                        }
                        """);
    }

    @Test
    void testGenerateModelWithCustomTypeAddsImport() throws IOException {
        var model = new FtlTemplateModel(
                "Report",
                "Report",
                PACKAGE_NAME,
                "Report.ftl",
                List.of(new FtlVariableModel("data", "ReportData", List.of("com.example.ReportData")))
        );

        sut.generateModel(model);

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "ReportModel"))
                .isPresent()
                .get()
                .isEqualTo("""
                        package com.example.templates;

                        import com.example.ReportData;
                        import lombok.AllArgsConstructor;
                        import lombok.Data;
                        import lombok.NoArgsConstructor;

                        /**
                         * Autogenerated data model for the FreeMarker template {@code Report.ftl}.
                         */
                        @Data
                        @AllArgsConstructor
                        @NoArgsConstructor
                        public class ReportModel {

                            private ReportData data;
                        }
                        """);
    }

    @Test
    void testGenerateModelWithMultipleVariables() throws IOException {
        var model = new FtlTemplateModel(
                "Invoice",
                "Invoice",
                PACKAGE_NAME,
                "Invoice.ftl",
                List.of(
                        new FtlVariableModel("recipient", "String", List.of()),
                        new FtlVariableModel("items", "List<LineItem>", List.of("java.util.List", "com.example.LineItem")),
                        new FtlVariableModel("total", "BigDecimal", List.of("java.math.BigDecimal"))
                )
        );

        sut.generateModel(model);

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "InvoiceModel"))
                .isPresent()
                .get()
                .isEqualTo("""
                        package com.example.templates;

                        import com.example.LineItem;
                        import java.math.BigDecimal;
                        import java.util.List;
                        import lombok.AllArgsConstructor;
                        import lombok.Data;
                        import lombok.NoArgsConstructor;

                        /**
                         * Autogenerated data model for the FreeMarker template {@code Invoice.ftl}.
                         */
                        @Data
                        @AllArgsConstructor
                        @NoArgsConstructor
                        public class InvoiceModel {

                            private String recipient;

                            private List<LineItem> items;

                            private BigDecimal total;
                        }
                        """);
    }

    @Test
    void testGenerateModelWithNoVariables() throws IOException {
        var model = new FtlTemplateModel(
                "Plain",
                "Plain",
                PACKAGE_NAME,
                "Plain.ftl",
                List.of()
        );

        sut.generateModel(model);

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "PlainModel"))
                .isPresent()
                .get()
                .isEqualTo("""
                        package com.example.templates;

                        import lombok.AllArgsConstructor;
                        import lombok.Data;
                        import lombok.NoArgsConstructor;

                        /**
                         * Autogenerated data model for the FreeMarker template {@code Plain.ftl}.
                         */
                        @Data
                        @AllArgsConstructor
                        @NoArgsConstructor
                        public class PlainModel {
                        }
                        """);
    }

    @Test
    void testImportsFromSamePackageAreExcluded() throws IOException {
        var model = new FtlTemplateModel(
                "Local",
                "Local",
                PACKAGE_NAME,
                "Local.ftl",
                List.of(new FtlVariableModel("item", "Item", List.of(PACKAGE_NAME + ".Item")))
        );

        sut.generateModel(model);

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "LocalModel"))
                .isPresent()
                .get()
                .satisfies(content -> assertThat(content).doesNotContain("import com.example.templates.Item"));
    }

    @Test
    void testGenerateFreemarkerTemplate() throws IOException {
        var model = new FtlTemplateModel(
                "Template",
                "Template",
                PACKAGE_NAME,
                "Template.ftl",
                Collections.emptyList()
        );

        sut.generateFreemarkerTemplate(PACKAGE_NAME, List.of(model));

        assertThat(sourceFileGenerator.getCreatedSourceFileNames())
                .containsExactly(PACKAGE_NAME + ".FreemarkerTemplate");

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "FreemarkerTemplate"))
                .isPresent()
                .get()
                .isEqualTo("""
                        package com.example.templates;

                        /**
                         * Autogenerated FreeMarker templates
                         */
                        public class FreemarkerTemplate<M> {

                            public static final FreemarkerTemplate<TemplateModel> TEMPLATE = new FreemarkerTemplate<>("Template.ftl", TemplateModel.class);

                            private final String templatePath;
                            private final Class<M> modelType;

                            private FreemarkerTemplate(String templatePath, Class<M> modelType) {
                                this.templatePath = templatePath;
                                this.modelType = modelType;
                            }

                            public String getTemplatePath() {
                                return templatePath;
                            }

                            public Class<M> getModelType() {
                                return modelType;
                            }
                        }
                        """);
    }

    @Test
    void testGenerateFreemarkerTemplateEngine() throws IOException {
        sut.generateFreemarkerTemplateEngine(PACKAGE_NAME);

        assertThat(sourceFileGenerator.getCreatedSourceFileNames())
                .containsExactly(PACKAGE_NAME + ".FreemarkerTemplateEngine");

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "FreemarkerTemplateEngine"))
                .isPresent()
                .get()
                .satisfies(content -> {
                    assertThat(content).startsWith("package com.example.templates;");
                    assertThat(content).contains("public class FreemarkerTemplateEngine");
                    assertThat(content).contains("public <M> void process(FreemarkerTemplate<M> template, M model, Writer writer)");
                });
    }

    @Test
    void testImportsAreSortedAlphabetically() throws IOException {
        var model = new FtlTemplateModel(
                "Sorted",
                "Sorted",
                PACKAGE_NAME,
                "Sorted.ftl",
                List.of(
                        new FtlVariableModel("z", "ZClass", List.of("com.zzz.ZClass")),
                        new FtlVariableModel("a", "AClass", List.of("com.aaa.AClass"))
                )
        );

        sut.generateModel(model);

        assertThat(sourceFileGenerator.getFileContent(PACKAGE_NAME, "SortedModel"))
                .isPresent()
                .get()
                .satisfies(content -> assertThat(content).containsSubsequence(
                        "import com.aaa.AClass;",
                        "import com.zzz.ZClass;",
                        "import lombok.AllArgsConstructor;"
                ));
    }
}
