<#ftl output_format="JavaScript">
<#-- @ftlvariable name="model" type="de.devx.project.commons.client.typescript.data.TypeScriptBrandedTypeModel" -->
<#-- @ftlvariable name="schemaImportPath" type="java.lang.String" -->
<#if schemaImportPath??><#t>
import { z } from 'zod';
import { ${model.name}Schema } from '${schemaImportPath}';

/**
 * Autogenerated branded type representing ${model.className}
 */
export type ${model.name} = z.infer<typeof ${model.name}Schema>;
<#else><#t>
/**
 * Autogenerated branded type representing ${model.className}
 */
export type ${model.name} = ${model.underlyingTsType} & { __brand: '${model.className}' };
</#if><#t>
