<#ftl output_format="JavaScript">
<#-- @ftlvariable name="model" type="de.devx.project.commons.client.typescript.data.TypeScriptBrandedTypeModel" -->
import { z } from 'zod';

/**
 * Autogenerated Zod schema for ${model.className}
 */
export const ${model.name}Schema = ${model.underlyingZodSchema}.brand<'${model.className}'>();
