<#ftl output_format="JavaScript">
<#-- @ftlvariable name="model" type="de.devx.project.commons.client.typescript.data.TypeScriptDTOModel" -->
<#-- @ftlvariable name="imports" type="java.util.Collection<de.devx.project.commons.client.typescript.data.TypeScriptImportModel>" -->
import { z } from 'zod';
<#if imports?has_content>
<#list imports as dependency>
import { ${dependency.identifiers?join(", ")} } from '${dependency.path}';
</#list>
</#if>

/**
 * Autogenerated Zod schema for ${model.className}
 */
export const ${model.name}Schema = <#if model.extendedDTO??>${model.extendedDTO.name}Schema.extend<#else>z.object</#if>({

<#list model.fields as field>
    ${field.name}: ${field.type.zodSchema}${field.type.optional?then(".optional()", "")},
</#list>

});
