<#ftl output_format="JavaScript">
<#-- @ftlvariable name="model" type="de.devx.project.commons.client.typescript.data.TypeScriptDTOModel" -->
<#-- @ftlvariable name="imports" type="java.util.Collection<de.devx.project.commons.client.typescript.data.TypeScriptImportModel>" -->
<#if imports?has_content>
    <#list imports as dependency>
        import { type ${dependency.identifiers?join(", ")} } from '${dependency.path}';
    </#list>

</#if>
/**
* Autogenerated DTO interface representing the java class ${model.className}
*/
export interface ${model.name}<#if model.typeArguments?has_content><${model.typeArguments?join(", ")}></#if><#if model.extendedDTO??> extends ${model.extendedDTO.name}</#if> {

<#list model.fields as field>
    ${field.name}${field.type.optional?then("?", "")}: ${field.type.name};
</#list>

}
