<#ftl output_format="JavaScript">
<#-- @ftlvariable name="model" type="de.devx.project.commons.client.typescript.data.TypeScriptDTOModel" -->
<#-- @ftlvariable name="imports" type="java.util.Collection<de.devx.project.commons.client.typescript.data.TypeScriptImportModel>" -->
<#-- @ftlvariable name="recursive" type="java.lang.Boolean" -->
<#-- @ftlvariable name="generic" type="java.lang.Boolean" -->
<#if imports?has_content>
<#list imports as dependency>
import { ${dependency.identifiers?join(", ")} } from '${dependency.path}';
</#list>
</#if>

<#if generic>
/**
 * Autogenerated Zod schema factory for ${model.className}
 */
export function create${model.name}Schema<${model.typeArguments?map(type -> type + " extends z.core.SomeType")?join(", ")}>(${model.typeArguments?map(type -> type + ": " + type)?join(", ")}) {
    return z.object({
        <#list model.fields as field>
        ${field.name}: <#if field.type.zodSchema??>${field.type.zodSchema}${field.type.optional?then(".optional()", "")}<#else>z.unknown()</#if>,
        </#list>
    });
}
<#else>
/**
 * Autogenerated Zod schema for ${model.className}
 */
export const ${model.name}Schema<#if recursive>: z.ZodType<${model.name}></#if> = <#if recursive>z.lazy(() => </#if><#if model.extendedDTO??>${model.extendedDTO.name}Schema.extend<#else>z.object</#if>({

<#list model.fields as field>
    ${field.name}: <#if field.type.zodSchema??>${field.type.zodSchema}${field.type.optional?then(".optional()", "")}<#else>z.unknown()</#if>,
</#list>

})<#if recursive>)</#if>;
</#if>
