<#ftl output_format="JavaScript">
<#-- @ftlvariable name="model" type="de.devx.project.commons.client.typescript.data.TypeScriptEnumModel" -->
import { z } from 'zod';

/**
 * Autogenerated Zod schema for ${model.className}
 */
export const ${model.name}Schema = z.enum([${model.values?map(value -> "'" + value + "'")?join(", ")}]);
