# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Build
        run: mvn install --file pom.xml -DskipTests

      - name: Run Unit Tests
        run: mvn verify --file pom.xml --fail-at-end
        continue-on-error: true

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: '**/target/test-reports/TEST-*.xml'

  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          name: Create Test Report
          artifact: test-reports
          path: '**/*.xml'
          reporter: java-junit

  clean-up:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Delete Unit Test Results
        uses: geekyeggo/delete-artifact@v5
        with:
          name: test-reports